version: 2.1

executors:
  default:
    working_directory: ~/project/
    shell: /bin/bash
    docker:
      - image: asteinh/docker:sympathor

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

################################################################################
# JOBS
################################################################################
jobs:
  # run unit tests
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: coverage run -m pytest -vv && coverage report
      - run:
          name: Generate HTML report
          command: coverage html
      - persist_to_workspace:
          root: ~/project/
          paths:
            - .coverage
            - coverage_html
      - store_artifacts:
          path: coverage_html

  publish_coverage:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - run:
          name: Upload coverage to codecov
          command: codecov --token=$CODECOV_TOKEN

  # build documentation with sphinx
  build_docs:
    executor: default
    steps:
      - checkout
      - run:
          name: Make HTML
          command: cd docs && make html
      - persist_to_workspace:
          root: ~/project/
          paths:
            - docs/build/html
      - store_artifacts:
          path: docs/build/

  # deploy documentation to github pages
  deploy_docs:
    working_directory: ~/project/
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - run:
          name: Move coverage report
          command: if [ -d coverage_html ]; then mv coverage_html docs/build/html/coverage; fi
      - gh-pages/deploy:
          build-dir: docs/build/html
          ssh-fingerprints: 11:75:2a:09:0c:45:4a:e9:79:91:ef:ed:a1:52:cd:eb

################################################################################
# WORKFLOWS
################################################################################

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - publish_coverage:
          requires:
            - test
          filters:
            branches:
              only: master
      - build_docs
      - deploy_docs:
          requires:
            - build_docs
          filters:
            branches:
              only: master
