version: 2.1

executors:
  default:
    working_directory: ~/project/
    shell: /bin/bash
    docker:
      - image: asteinh/docker:sympathor

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

################################################################################
# JOBS
################################################################################
jobs:
  # run unit tests
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: ls -l

  # build documentation with sphinx
  build_docs:
    executor: default
    steps:
      - checkout
      - run:
          name: Make HTML
          command: cd docs && make html
      - persist_to_workspace:
          root: ~/project/
          paths:
            - docs/build/html
      - store_artifacts:
          path: docs/build/

  # deploy documentation to github pages
  deploy_docs:
    working_directory: ~/project/
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - gh-pages/deploy:
          build-dir: docs/build/html
          ssh-fingerprints: 90:82:6a:ce:4b:38:68:9c:76:87:6a:e2:1e:fd:7f:b3

################################################################################
# WORKFLOWS
################################################################################

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build_docs
      - deploy_docs:
          requires:
            - build_docs
          # filters:
          #   branches:
          #     only: master
